### ISSUE TITLE
How to refine the parameter of combine_loss

### ISSUE THREAD

**Issue by Paleve** [sirius-ai/MobileFaceNet_TF#18]
Thanks for you contribution, and could you release the parameter of combine_loss or tell me how to refine them

**Comment by sirius-ai** [comment]
I will try that later.

**Comment by sirius-ai** [comment]
[see](https://github.com/sirius-ai/MobileFaceNet_TF/commit/c6102da6044908713f06faa11374d66b887045bc)

**Comment by siyiding1216** [comment]
The combined loss was trained well but it stopped at around 60k iter.
And it complains about Shapes of all inputs must match: values[0].shape = [90] != values[1].shape = [13]...
Do you have an idea why?

Traceback (most recent call last):
  File "xxx/anaconda3/envs/tensorflow1_131/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1334, in _do_call
    return fn(*args)
  File "xxx/envs/tensorflow1_131/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1319, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "xxx/anaconda3/envs/tensorflow1_131/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1407, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Shapes of all inputs must match: values[0].shape = [90] != values[1].shape = [13]
         [[{{node combine_loss/stack}}]]
         [[{{node MobileFaceNet/Logits/Conv/kernel/Regularizer/l2_regularizer}}]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "train_nets_finetune.py", line 235, in <module>
    feed_dict=feed_dict)
  File "/xxx/anaconda3/envs/tensorflow1_131/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 929, in run
    run_metadata_ptr)
  File "/xxx/anaconda3/envs/tensorflow1_131/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1152, in _run
    feed_dict_tensor, options, run_metadata)
  File "/xxx/anaconda3/envs/tensorflow1_131/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1328, in _do_run
    run_metadata)
  File "/xxx/anaconda3/envs/tensorflow1_131/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1348, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Shapes of all inputs must match: values[0].shape = [90] != values[1].shape = [13]
         [[node combine_loss/stack (defined at /xxx/MobileFaceNet_TF/losses/face_losses.py:103) ]]
         [[node MobileFaceNet/Logits/Conv/kernel/Regularizer/l2_regularizer (defined at /xxx/MobileFaceNet_TF/nets/MobileFaceNet.py:224) ]]

Caused by op 'combine_loss/stack', defined at:
  File "train_nets_finetune.py", line 155, in <module>
    inference_loss, logit = combine_loss(embeddings, labels, args.train_batch_size, args.class_number, w_init_method)
  File "/xxx/MobileFaceNet_TF/losses/face_losses.py", line 103, in combine_loss
    ordinal_y = tf.stack([ordinal, labels], axis=1)
  File "/xxx/anaconda3/envs/tensorflow1_131/lib/python3.6/site-packages/tensorflow/python/util/dispatch.py", line 180, in wrapper
    return target(*args, **kwargs)
  File "/xxx/anaconda3/envs/tensorflow1_131/lib/python3.6/site-packages/tensorflow/python/ops/array_ops.py", line 1005, in stack
    return gen_array_ops.pack(values, axis=axis, name=name)
  File "/xxx/anaconda3/envs/tensorflow1_131/lib/python3.6/site-packages/tensorflow/python/ops/gen_array_ops.py", line 5448, in pack
    "Pack", values=values, axis=axis, name=name)
  File "/xxx/anaconda3/envs/tensorflow1_131/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 788, in _apply_op_helper
    op_def=op_def)
  File "/xxx/anaconda3/envs/tensorflow1_131/lib/python3.6/site-packages/tensorflow/python/util/deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "/xxx/anaconda3/envs/tensorflow1_131/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 3300, in create_op
    op_def=op_def)
  File "/xxx/anaconda3/envs/tensorflow1_131/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1801, in __init__
    self._traceback = tf_stack.extract_stack()

InvalidArgumentError (see above for traceback): Shapes of all inputs must match: values[0].shape = [90] != values[1].shape = [13]
         [[node combine_loss/stack (defined at /xxx/MobileFaceNet_TF/losses/face_losses.py:103) ]]
         [[node MobileFaceNet/Logits/Conv/kernel/Regularizer/l2_regularizer (defined at /xxx/MobileFaceNet_TF/nets/MobileFaceNet.py:224) ]]
