### ISSUE TITLE
Trying to read ckpt but get ValueError:

### ISSUE THREAD

**Issue by neesetifa** [sirius-ai/MobileFaceNet_TF#78]
Just try to do a simple forward inference, all the codes are just copy-and-paste from test_nets.py, nothing's changed except added compat.v1 for I'm using TF 2.x
```
def get_model_filenames(model_dir):
    files = os.listdir(model_dir)
    meta_files = [s for s in files if s.endswith('.meta')]
    if len(meta_files) == 0:
        raise ValueError('No meta file found in the model directory (%s)' % model_dir)
    elif len(meta_files) > 1:
        raise ValueError('There should not be more than one meta file in the model directory (%s)' % model_dir)
    meta_file = meta_files[0]
    ckpt = tf.compat.v1.train.get_checkpoint_state(model_dir)
    if ckpt and ckpt.model_checkpoint_path:
        ckpt_file = os.path.basename(ckpt.model_checkpoint_path)
        return meta_file, ckpt_file

    meta_files = [s for s in files if '.ckpt' in s]
    max_step = -1
    for f in files:
        step_str = re.match(r'(^model-[\w\- ]+.ckpt-(\d+))', f)
        if step_str is not None and len(step_str.groups()) >= 2:
            step = int(step_str.groups()[1])
            if step > max_step:
                max_step = step
                ckpt_file = step_str.groups()[0]
    return meta_file, ckpt_file


def load_model(model):
    model_exp = os.path.expanduser(model)
    if (os.path.isfile(model_exp)):
        print('Model filename: %s' % model_exp)
        with tf.compat.v1.gfile.FastGFile(model_exp, 'rb') as f:
            graph_def = tf.compat.v1.GraphDef()
            graph_def.ParseFromString(f.read())
            tf.compat.v1.import_graph_def(graph_def, name='')
    else:
        print('Model directory: %s' % model_exp)
        meta_file, ckpt_file = get_model_filenames(model_exp)

        print('Metagraph file: %s' % meta_file)
        print('Checkpoint file: %s' % ckpt_file)

        saver = tf.compat.v1.train.import_meta_graph(os.path.join(model_exp, meta_file))
        saver.restore(tf.compat.v1.get_default_session(), os.path.join(model_exp, ckpt_file))


def main():
    image = load_image('xxx.jpg')
    load_model('./')   # all the pretrained file from arch/pretrained_model/ are put in the same directory

    with tf.compat.v1.Graph().as_default():
        with tf.compat.v1.Session() as sess:
            pdb.set_trace()
            inputs_placeholder = tf.compat.v1.get_default_graph().get_tensor_by_name("input:0")
            embeddings = tf.compat.v1.get_default_graph().get_tensor_by_name("embeddings:0")
            feed_dict = {inputs_placeholder: image}
            output = sess.run(embeddings, feed_dict=feed_dict)
           
```
But get following error:
```
Model directory: ./
Metagraph file: MobileFaceNet_TF.ckpt.meta
Checkpoint file: MobileFaceNet_TF.ckpt
Traceback (most recent call last):
  File "aa.py", line 79, in <module>
    main()
  File "aa.py", line 67, in main
    load_model('./')
  File "aa.py", line 61, in load_model
    saver = tf.compat.v1.train.import_meta_graph(os.path.join(model_exp, meta_file))
  File "/usr/lib/python3.8/site-packages/tensorflow/python/training/saver.py", line 1460, in import_meta_graph
    return _import_meta_graph_with_return_elements(meta_graph_or_file,
  File "/usr/lib/python3.8/site-packages/tensorflow/python/training/saver.py", line 1481, in _import_meta_graph_with_return_elements
    meta_graph.import_scoped_meta_graph_with_return_elements(
  File "/usr/lib/python3.8/site-packages/tensorflow/python/framework/meta_graph.py", line 794, in import_scoped_meta_graph_with_return_elements
    imported_return_elements = importer.import_graph_def(
  File "/usr/lib/python3.8/site-packages/tensorflow/python/util/deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "/usr/lib/python3.8/site-packages/tensorflow/python/framework/importer.py", line 400, in import_graph_def
    return _import_graph_def_internal(
  File "/usr/lib/python3.8/site-packages/tensorflow/python/framework/importer.py", line 501, in _import_graph_def_internal
    raise ValueError(str(e))
ValueError: Node 'gradients/MobileFaceNet/Logits/LinearConv1x1/BatchNorm/cond/FusedBatchNorm_1_grad/FusedBatchNormGrad' has an _output_shapes attribute inconsistent with the GraphDef for output #3: Dimension 0 in both shapes must be equal, but are 0 and 192. Shapes are [0] and [192].
```
any help or hint?

**Comment by wei8171023** [comment]
吧--embedding_size默认值设为192

**Comment by howell0203** [comment]
> 
不行呀兄弟 我改了还是错
Pre-trained model: ./arch/pretrained_model
2022-11-15 21:03:04.953915: I C:\tf_jenkins\workspace\rel-win\M\windows-gpu\PY\36\tensorflow\core\platform\cpu_feature_guard.cc:137] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX AVX2
2022-11-15 21:03:06.798728: I C:\tf_jenkins\workspace\rel-win\M\windows-gpu\PY\36\tensorflow\core\common_runtime\gpu\gpu_device.cc:1105] Found device 0 with properties: 
name: NVIDIA GeForce RTX 2060 major: 7 minor: 5 memoryClockRate(GHz): 1.755
pciBusID: 0000:01:00.0
totalMemory: 6.00GiB freeMemory: 4.93GiB
2022-11-15 21:03:06.815754: I C:\tf_jenkins\workspace\rel-win\M\windows-gpu\PY\36\tensorflow\core\common_runtime\gpu\gpu_device.cc:1195] Creating TensorFlow device (/device:GPU:0) -> (device: 0, name: NVIDIA GeForce RTX 2060, pci bus id: 0000:01:00.0, compute capability: 7.5)
Restoring pretrained model: ./arch/pretrained_model
model_checkpoint_path: "./arch/pretrained_model\\MobileFaceNet_TF.ckpt"
all_model_checkpoint_paths: "./arch/pretrained_model\\MobileFaceNet_TF.ckpt"

Traceback (most recent call last):
  File "E:\Anaconda\envs\tensorflow1.5\lib\site-packages\tensorflow\python\client\session.py", line 1350, in _do_call
    return fn(*args)
  File "E:\Anaconda\envs\tensorflow1.5\lib\site-packages\tensorflow\python\client\session.py", line 1329, in _run_fn
    status, run_metadata)
  File "E:\Anaconda\envs\tensorflow1.5\lib\site-packages\tensorflow\python\framework\errors_impl.py", line 473, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.InvalidArgumentError: Assign requires shapes of both tensors to match. lhs shape= [192,10572] rhs shape= [192,85742]
	 [[Node: save/Assign_293 = Assign[T=DT_FLOAT, _class=["loc:@insightface_loss/embedding_weights"], use_locking=true, validate_shape=true, _device="/job:localhost/replica:0/task:0/device:GPU:0"](insightface_loss/embedding_weights, save/RestoreV2_293/_709)]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\ChromeDownloads\MobileFaceNet_TF-master\train_nets.py", line 212, in <module>
    saver.restore(sess, ckpt.model_checkpoint_path)
  File "E:\Anaconda\envs\tensorflow1.5\lib\site-packages\tensorflow\python\training\saver.py", line 1686, in restore
    {self.saver_def.filename_tensor_name: save_path})
  File "E:\Anaconda\envs\tensorflow1.5\lib\site-packages\tensorflow\python\client\session.py", line 895, in run
    run_metadata_ptr)
  File "E:\Anaconda\envs\tensorflow1.5\lib\site-packages\tensorflow\python\client\session.py", line 1128, in _run
    feed_dict_tensor, options, run_metadata)
  File "E:\Anaconda\envs\tensorflow1.5\lib\site-packages\tensorflow\python\client\session.py", line 1344, in _do_run
    options, run_metadata)
  File "E:\Anaconda\envs\tensorflow1.5\lib\site-packages\tensorflow\python\client\session.py", line 1363, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Assign requires shapes of both tensors to match. lhs shape= [192,10572] rhs shape= [192,85742]
	 [[Node: save/Assign_293 = Assign[T=DT_FLOAT, _class=["loc:@insightface_loss/embedding_weights"], use_locking=true, validate_shape=true, _device="/job:localhost/replica:0/task:0/device:GPU:0"](insightface_loss/embedding_weights, save/RestoreV2_293/_709)]]

Caused by op 'save/Assign_293', defined at:
  File "E:\ChromeDownloads\MobileFaceNet_TF-master\train_nets.py", line 201, in <module>
    saver = tf.train.Saver(tf.trainable_variables(), max_to_keep=args.saver_maxkeep)
  File "E:\Anaconda\envs\tensorflow1.5\lib\site-packages\tensorflow\python\training\saver.py", line 1239, in __init__
    self.build()
  File "E:\Anaconda\envs\tensorflow1.5\lib\site-packages\tensorflow\python\training\saver.py", line 1248, in build
    self._build(self._filename, build_save=True, build_restore=True)
  File "E:\Anaconda\envs\tensorflow1.5\lib\site-packages\tensorflow\python\training\saver.py", line 1284, in _build
    build_save=build_save, build_restore=build_restore)
  File "E:\Anaconda\envs\tensorflow1.5\lib\site-packages\tensorflow\python\training\saver.py", line 765, in _build_internal
    restore_sequentially, reshape)
  File "E:\Anaconda\envs\tensorflow1.5\lib\site-packages\tensorflow\python\training\saver.py", line 440, in _AddRestoreOps
    assign_ops.append(saveable.restore(tensors, shapes))
  File "E:\Anaconda\envs\tensorflow1.5\lib\site-packages\tensorflow\python\training\saver.py", line 160, in restore
    self.op.get_shape().is_fully_defined())
  File "E:\Anaconda\envs\tensorflow1.5\lib\site-packages\tensorflow\python\ops\state_ops.py", line 276, in assign
    validate_shape=validate_shape)
  File "E:\Anaconda\envs\tensorflow1.5\lib\site-packages\tensorflow\python\ops\gen_state_ops.py", line 62, in assign
    use_locking=use_locking, name=name)
  File "E:\Anaconda\envs\tensorflow1.5\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "E:\Anaconda\envs\tensorflow1.5\lib\site-packages\tensorflow\python\framework\ops.py", line 3160, in create_op
    op_def=op_def)
  File "E:\Anaconda\envs\tensorflow1.5\lib\site-packages\tensorflow\python\framework\ops.py", line 1625, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

InvalidArgumentError (see above for traceback): Assign requires shapes of both tensors to match. lhs shape= [192,10572] rhs shape= [192,85742]
	 [[Node: save/Assign_293 = Assign[T=DT_FLOAT, _class=["loc:@insightface_loss/embedding_weights"], use_locking=true, validate_shape=true, _device="/job:localhost/replica:0/task:0/device:GPU:0"](insightface_loss/embedding_weights, save/RestoreV2_293/_709)]]
